blog/urls.py
from django.conf.urls import url

app_name='blog'
urlpatterns = [
	url(r'^$', 'blog.views.story_list', name='story_list'),
	url(r'^createstory', 'blog.views.story_create'),
	url(r'^(?P<slug>[\w-]+)/$', 'blog.views.story_detail', name='story_detail'),
	url(r'^(?P<slug>[\w-]+)/edit$', 'blog.views.story_update', name='story_update'),
	url(r'^(?P<slug>[\w-]+)/delete$', 'blog.views.story_delete', name='story_delete'),

]

core/urls.py
from django.conf.urls import url, include


app_name='core'
urlpatterns = [
	url(r'^$', 'core.views.home', name='home'),
	url(r'^about/$', 'core.views.about', name='about'),
]

djangokids/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^tutorials/', include('tutorial.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^events/', include('event.urls')),
    url(r'^', include('core.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/urls.py
from django.conf.urls import url

app_name="tutorial"
urlpatterns = [
	url(r'^$', 'tutorial.views.tutorial_list', name='tutorial_list'),
	url(r'^createtutorial/$', 'tutorial.views.tutorial_create', name='tutorial_create'),
	url(r'^(?P<tutorial_slug>[\w-]+)/edit/$', 'tutorial.views.tutorial_update', name='tutorial_update'),
	url(r'^(?P<tutorial_slug>[\w-]+)/delete/$', 'tutorial.views.tutorial_delete', name='tutorial_delete'),	
	
	url(r'^(?P<tutorial_slug>[\w-]+)/$', 'tutorial.views.lesson_list', name='lesson_list'),
	url(r'^(?P<tutorial_slug>[\w-]+)/createlesson/$', 'tutorial.views.lesson_create'),
	url(r'^(?P<tutorial_slug>[\w-]+)/(?P<lesson_slug>[\w-]+)/$', 'tutorial.views.lesson_detail', name='lesson_detail'),
	url(r'^(?P<tutorial_slug>[\w-]+)/(?P<lesson_slug>[\w-]+)/edit/$', 'tutorial.views.lesson_update', name='lesson_update'),
	url(r'^(?P<tutorial_slug>[\w-]+)/(?P<lesson_slug>[\w-]+)/delete/$', 'tutorial.views.lesson_delete', name='lesson_delete' ),
]

templates/about.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Thông tin về chúng tôi </h1>

<h2>Góp ý cho chúng tôi</h2>
<form method="POST" action="">{% csrf_token %}
	{{ form | crispy }}
	<input type="submit" value="Send"></input>
</form>

{% endblock content %}

templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="description" content="">
	<meta name="author" content="">

	{% include "header_css.html" %}
	<title>{% block title %}DjangoKids{% endblock title %}</title>
    
    {% block stylelesson %}
    {% endblock %}
    {% block styleevent %}
    {% endblock %}
</head>

<body>

	{% include "navbar.html" %}

	{% block jumbotron %}
	{% endblock jumbotron %}

    {% block contenthome %}
    {% endblock %}

	{% block head_extra %}
    {% endblock head_extra %}

    {% block navlesson %}
    {% endblock navlesson %}

    {% block content_lesson_detail %}
    {% endblock %}

    <div class="container">
      <!-- Example row of columns -->  
    <div class=row>
        <div class="col-sm-8 col-sm-offset-2">
            {% block content %}
	       {% endblock content %}
        </div>
    </div>  
	</div> <!-- /container -->

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    {% block footer %}
    {% endblock footer%}



    {% include "javascript.html" %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

    <script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
    <script type="text/javascript"> 
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()
            console.log(content)
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent) 
    })
})
</script>
</body>
</html>

templates/header_css.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-static-top.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jumbotron.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/my-customize.css' %}">

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block jumbotron %}
	<!-- Gioi thieu ve du an -->
    <div class="jumbotron">
      <div class="container">
      <div class="row">
      <div class="col-sm-6">
     	<h1>Django kids</h1>
        <p>Django kids mong muốn kết nối các lập trình viên để tạo ra công cụ giúp cho học sinh ở VN có thể tự học lập trình online để giải quyết các bài toán thực tế. </p>
        <p><a class="btn btn-success btn-lg" href="{% url 'tutorial:tutorial_list' %}" role="button">Bắt đầu nào &raquo;</a></p>
      </div>

      <div class="col-sm-6">
        <div class="thumbnail" >
        	<img src="{% static 'img/django.png' %}" class='img-responsive'>
        </div>
      </div>
      </div>
      </div>
    </div>
{% endblock jumbotron %}

{% block contenthome %}



<!-- Nhung bai huong dan -->
<div class="container">
  <h2 class="text-align-center">Các khóa học python-django</h2><hr>
  <div class="row">
  {% for instance in tutorials  %}
  <div class="col-sm-4">
    <div class="thumbnail">
    <a href="{{ instance.get_absolute_url }}">
      <img src="{{ instance.photo }}" class="responsive">
    </a>
    <div class="caption">
      <h3>
        <a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a>
      </h3>
      <p>
        <a href="{{ instance.get_absolute_url }}" class="btn btn-success">Bắt đầu</a><small> {{ instance.description }}</small>
      </p>
    </div>
    </div>
  </div>
  {% endfor %}
</div>
</div>


<!-- Nhung cau chuyen -->
<dir class="container">
<h2 class="text-align-center">Những câu chuyện </h2><hr>
  <div class="row">
    <div class="col-sm-6">
      <p style="font-size: 20px">Chúng tôi sẽ liên tục đăng lên những câu chuyện dành cho bạn để bạn có thêm cảm hứng để học Python-Django.</p> 
    </div>

    <div class="col-sm-6">
      {% for story in stories %}
       <li><p style="font-size: 20px"><a href="{{ story.get_absolute_url }}">{{ story.title }}</a></p></li>   
      {% endfor %}
    </div>
  </div>
</dir>

<!-- Nhung su kien sap dien ra -->

<div class="container">
  <h2 class="text-align-center">Những sự kiện sắp diễn ra</h2><hr>
  <div class="row">
  {% for event in events  %}
    <div class="col-sm-4">
      <div class="thumbnail">
        <a href="{{ event.get_absolute_url }}">
          <img src="{{ event.photo }}">
        </a>
      
      <div class="caption">
        <h3><a href="{{ instance.get_absolute_url }}">{{ instance.name }}</a></h3>
        <p> {{ event.description }}</p>
        <a href="{{ event.get_absolute_url }}" class="btn btn-success btn-lg">Tham gia</a>
      </div>
      </div>
    </div>
  {% endfor %}

  </div>
</div>
  

<!-- Hay lien he voi chung toi -->
<div class="container">
  <h2>Hãy liên hệ với chúng tôi </h2>
  <p class="lead">Mọi ý kiến đóng góp xin gửi về gmail: Djangokids@gmail.com</p>
  <p class="lead">Chúng tôi mong rằng sẽ sớm hoàn thành sản phẩm mang lại sự hứng thú khi học Python-Django. </p>
  <p class="lead">Giúp mọi người tự mình tạo ra những sản phẩm ứng dụng vào thực tế.</p>


</div>


{% endblock contenthome%}

{% block content %}
{% endblock content%}

{% block footer %}
    <footer style="background-color: #f9f7f7; padding-top: 20px;">
    <div class="container">
      <h2 style="color: #0C3C26">Django kids</h2><hr>
      <p>Email: Djangokids@gmail.com</p>
      <p>Điện thoại: 01692632585</p>
      <p>Địa chỉ: 36 Duy Tân Ozatea</p>
    </div>

    </footer>
{% endblock footer%}

templates/javascript.html
{% load staticfiles %}


<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>
<script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

templates/navbar.html
{% load staticfiles %}
    <nav class="navbar navbar-fixed-top navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar" >
            <!-- <span class="sr-only">Toggle navigation</span>
             -->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{% static 'img/logo-django-kid-3.png' %}"style="width:150px; height:50px;padding-bottom: 3px;"></a>
        </div>
        <div id="mynavbar" class="collapse navbar-collapse ">
          <ul class="nav navbar-nav">
            <li><a href="/tutorials" class="white">Khóa học</a></li>
            <li><a href="/blog" class="white">Blog</a></li>
            <li><a href="/events" class="white">Comming soon</a></li>
            <li><a href="/about" class="white">About</a></li> 
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if not request.user.is_anonymous %}
          <li><a href="{% url 'auth_logout' %}" class="white">Đăng xuất ({{ request.user.username }})</a></li>          
          {% else %}
          <li><a href="{% url 'registration_register' %}" class="white">Đăng kí</a></li>
          {% endif %}
          </ul>
          {% if request.user.is_anonymous  and 'accounts/login' not in request.get_full_path %}
          <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">{% csrf_token %}
            <div class="form-group">
              <input type="text" placeholder="Tên người dùng"  name="username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Mật khẩu" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success" class="white">Đăng nhập</button>
          </form>
          </ul>
           {% endif %}

        </div><!--/.navbar-collapse -->
      </div>
    </nav> <!-- end navbar -->